# Generated by Django 5.1.6 on 2025-02-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('kirovstat', '0001_initial'), ('kirovstat', '0002_teams'), ('kirovstat', '0003_alter_teams_t_aka'), ('kirovstat', '0004_alter_teams_t_foto'), ('kirovstat', '0005_alter_teams_t_foto_alter_teams_t_page'), ('kirovstat', '0006_games'), ('kirovstat', '0007_gmdata'), ('kirovstat', '0008_alter_games_options_alter_gmdata_options_and_more'), ('kirovstat', '0009_alter_game_type_options'), ('kirovstat', '0010_alter_game_type_type_name_alter_games_g_date_and_more'), ('kirovstat', '0011_alter_games_options')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Вид игры')),
            ],
            options={
                'ordering': ['type_name'],
                'verbose_name': 'Тип игры',
                'verbose_name_plural': 'Типы игры',
            },
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('t_page', models.URLField(default='http://rudagames.ru')),
                ('t_foto', models.CharField(default='.foto.jpg', max_length=50, verbose_name='Фото команды')),
                ('t_aka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kirovstat.teams')),
                ('time_data', models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано')),
            ],
            options={
                'ordering': ['t_name'],
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='Название игры', max_length=50)),
                ('g_date', models.DateField(verbose_name='Дата игры')),
                ('g_sets', models.IntegerField(verbose_name='Количесто туров')),
                ('g_url', models.URLField(default='https://vk.com/mzgb_kir', verbose_name='Ссылка на игра в ВК')),
                ('g_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kirovstat.game_type')),
                ('time_data', models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано')),
            ],
            options={
                'ordering': ['-g_date'],
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игра',
            },
        ),
        migrations.CreateModel(
            name='gmdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_set1', models.FloatField(max_length=5, verbose_name='Тур 1')),
                ('gd_set2', models.FloatField(max_length=5, verbose_name='Тур 2')),
                ('gd_set3', models.FloatField(max_length=5, verbose_name='Тур 3')),
                ('gd_set4', models.FloatField(max_length=5, verbose_name='Тур 4')),
                ('gd_set5', models.FloatField(max_length=5, verbose_name='Тур 5')),
                ('gd_set6', models.FloatField(max_length=5, verbose_name='Тур 6')),
                ('gd_set7', models.FloatField(max_length=5, verbose_name='Тур 7')),
                ('gd_set8', models.FloatField(max_length=5, verbose_name='Тур 8')),
                ('gd_set9', models.FloatField(max_length=5, verbose_name='Тур 9')),
                ('gd_set10', models.FloatField(max_length=5, verbose_name='Тур 10')),
                ('gd_place', models.IntegerField(verbose_name='Место')),
                ('gd_summ', models.FloatField(max_length=8, verbose_name='Сумма очков')),
                ('gd_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirovstat.games')),
                ('gd_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirovstat.teams')),
                ('time_data', models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано')),
            ],
            options={
                'ordering': ['time_data'],
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
    ]
