# Generated by Django 5.1.6 on 2025-02-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('t_page', models.URLField()),
                ('t_foto', models.FilePathField()),
                ('t_aka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kirovstat.teams')),
            ],
        ),
    ]
