# Generated by Django 5.1.6 on 2025-02-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0002_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='t_aka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kirovstat.teams'),
        ),
    ]
