# Generated by Django 5.1.6 on 2025-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0003_alter_teams_t_aka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='t_foto',
            field=models.CharField(max_length=50),
        ),
    ]
