# Generated by Django 5.1.6 on 2025-02-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0004_alter_teams_t_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='t_foto',
            field=models.CharField(default='.foto.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='t_page',
            field=models.URLField(default='http://rudagames.ru'),
        ),
    ]
