# Generated by Django 5.1.6 on 2025-02-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0005_alter_teams_t_foto_alter_teams_t_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='Название игры', max_length=50)),
                ('g_date', models.DateField()),
                ('g_sets', models.IntegerField()),
                ('g_url', models.URLField(default='https://vk.com/mzgb_kir')),
                ('g_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kirovstat.game_type')),
            ],
        ),
    ]
