# Generated by Django 5.1.6 on 2025-02-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0006_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='gmdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_set1', models.FloatField(max_length=5)),
                ('gd_set2', models.FloatField(max_length=5)),
                ('gd_set3', models.FloatField(max_length=5)),
                ('gd_set4', models.FloatField(max_length=5)),
                ('gd_set5', models.FloatField(max_length=5)),
                ('gd_set6', models.FloatField(max_length=5)),
                ('gd_set7', models.FloatField(max_length=5)),
                ('gd_set8', models.FloatField(max_length=5)),
                ('gd_set9', models.FloatField(max_length=5)),
                ('gd_set10', models.FloatField(max_length=5)),
                ('gd_place', models.IntegerField(max_length=2)),
                ('gd_summ', models.FloatField(max_length=8)),
                ('gd_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirovstat.games')),
                ('gd_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirovstat.teams')),
            ],
        ),
    ]
