# Generated by Django 5.1.6 on 2025-02-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0007_gmdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['g_name'], 'verbose_name': 'Игры', 'verbose_name_plural': 'Игра'},
        ),
        migrations.AlterModelOptions(
            name='gmdata',
            options={'ordering': ['time_data'], 'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['t_name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AddField(
            model_name='games',
            name='time_data',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='gmdata',
            name='time_data',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='teams',
            name='time_data',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kirovstat.game_type', verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_place',
            field=models.IntegerField(verbose_name=2),
        ),
    ]
