# Generated by Django 5.1.6 on 2025-02-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0008_alter_games_options_alter_gmdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_type',
            options={'ordering': ['type_name'], 'verbose_name': 'Тип игры', 'verbose_name_plural': 'Типы игры'},
        ),
    ]
