# Generated by Django 5.1.6 on 2025-02-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0009_alter_game_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_type',
            name='type_name',
            field=models.CharField(max_length=50, verbose_name='Вид игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_date',
            field=models.DateField(verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_sets',
            field=models.IntegerField(verbose_name='Количесто туров'),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kirovstat.game_type'),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_url',
            field=models.URLField(default='https://vk.com/mzgb_kir', verbose_name='Ссылка на игра в ВК'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_place',
            field=models.IntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set1',
            field=models.FloatField(max_length=5, verbose_name='Тур 1'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set10',
            field=models.FloatField(max_length=5, verbose_name='Тур 10'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set2',
            field=models.FloatField(max_length=5, verbose_name='Тур 2'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set3',
            field=models.FloatField(max_length=5, verbose_name='Тур 3'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set4',
            field=models.FloatField(max_length=5, verbose_name='Тур 4'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set5',
            field=models.FloatField(max_length=5, verbose_name='Тур 5'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set6',
            field=models.FloatField(max_length=5, verbose_name='Тур 6'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set7',
            field=models.FloatField(max_length=5, verbose_name='Тур 7'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set8',
            field=models.FloatField(max_length=5, verbose_name='Тур 8'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set9',
            field=models.FloatField(max_length=5, verbose_name='Тур 9'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_summ',
            field=models.FloatField(max_length=8, verbose_name='Сумма очков'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='t_foto',
            field=models.CharField(default='.foto.jpg', max_length=50, verbose_name='Фото команды'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='t_name',
            field=models.CharField(max_length=50, verbose_name='Название команды'),
        ),
    ]
