# Generated by Django 5.1.6 on 2025-02-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0010_alter_game_type_type_name_alter_games_g_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['-g_date'], 'verbose_name': 'Игры', 'verbose_name_plural': 'Игра'},
        ),
    ]
