# Generated by Django 5.1.6 on 2025-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0001_squashed_0011_alter_games_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set1',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 1'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set10',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 10'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set2',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 2'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set3',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 3'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set4',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 4'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set5',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 5'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set6',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 6'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set7',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 7'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set8',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 8'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_set9',
            field=models.FloatField(default=300, max_length=5, verbose_name='Тур 9'),
        ),
    ]
