# Generated by Django 4.2.19 on 2025-03-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0012_alter_gmdata_gd_set1_alter_gmdata_gd_set10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='g_teams',
            field=models.ImageField(default=1, null=True, upload_to='', verbose_name='Количество команда'),
        ),
    ]
