# Generated by Django 4.2.19 on 2025-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0013_games_g_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='g_teams',
            field=models.IntegerField(default=1, null=True, verbose_name='Количество команда'),
        ),
    ]
