# Generated by Django 5.1.7 on 2025-04-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0014_alter_games_g_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='g_name',
            field=models.CharField(default='Название игры', max_length=100),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_sets',
            field=models.IntegerField(default=5, verbose_name='Количесто туров'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirovstat.games', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gmdata',
            name='gd_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kirovstat.teams', verbose_name='Команда'),
        ),
    ]
