# Generated by Django 5.1.7 on 2025-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0015_alter_games_g_name_alter_games_g_sets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weekr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('week_points_tuz', models.CharField(default='Очки команд за музыкалку', max_length=500)),
                ('week_points_сlass', models.CharField(default='Очки команд за классику', max_length=500)),
                ('week_points_summ', models.CharField(default='Очки команд всего', max_length=500)),
                ('week_rating_tuz', models.CharField(default='10 рейтинга за музыкалку', max_length=200)),
                ('week_rating_сlass', models.CharField(default='10 рейтинга за классику', max_length=200)),
                ('week_rating_summ', models.CharField(default='10 рейтинга всего', max_length=200)),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика по неделям',
                'ordering': ['week_start'],
            },
        ),
    ]
