# Generated by Django 5.1.7 on 2025-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0016_weekr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekr',
            name='week_points_summ',
            field=models.CharField(max_length=500, verbose_name='Очки команд всего'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_points_tuz',
            field=models.CharField(max_length=500, verbose_name='Очки команд за музыкалку'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_points_сlass',
            field=models.CharField(max_length=500, verbose_name='Очки команд за классику'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_summ',
            field=models.CharField(max_length=200, verbose_name='10 рейтинга всего'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_tuz',
            field=models.CharField(max_length=200, verbose_name='10 рейтинга за музыкалку'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_сlass',
            field=models.CharField(max_length=200, verbose_name='10 рейтинга за классику'),
        ),
    ]
