# Generated by Django 5.1.7 on 2025-04-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0017_alter_weekr_week_points_summ_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekr',
            old_name='week_points_сlass',
            new_name='week_points_class',
        ),
        migrations.RenameField(
            model_name='weekr',
            old_name='week_rating_сlass',
            new_name='week_rating_class',
        ),
    ]
