# Generated by Django 5.1.7 on 2025-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0018_rename_week_points_сlass_weekr_week_points_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_class',
            field=models.CharField(max_length=800, verbose_name='Рейтинг за классику'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_summ',
            field=models.CharField(max_length=800, verbose_name='Рейтинг всего'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_tuz',
            field=models.CharField(max_length=800, verbose_name='Рейтинг за музыкалку'),
        ),
    ]
