# Generated by Django 5.1.7 on 2025-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirovstat', '0019_alter_weekr_week_rating_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_class',
            field=models.CharField(max_length=1200, verbose_name='Рейтинг за классику'),
        ),
        migrations.AlterField(
            model_name='weekr',
            name='week_rating_summ',
            field=models.CharField(max_length=2000, verbose_name='Рейтинг всего'),
        ),
    ]
